"""Build an offline HTML catalog from a building workspace's evidence and incoming manifests.

Usage: python tools/reference-catalog/build.py reconstructions/<id>/work
Writes <workspace>/references/catalog/index.html and thumbnails, and <workspace>/references/INDEX.md.
The catalog shows private evidence: it stays in the gitignored work/ folder.
"""
from pathlib import Path
import json,hashlib,sys
from PIL import Image,ImageOps
P=(Path(sys.argv[1]) if len(sys.argv)>1 else Path.cwd()).resolve();R=P/'references';T=R/'catalog';T.mkdir(parents=True,exist_ok=True)
m=json.loads((R/'manifest.json').read_text(encoding='utf-8'));rows=m['assets'];incoming=R/'incoming';ip=incoming/'manifest.json';pending=json.loads(ip.read_text(encoding='utf-8')).get('entries',[])if ip.exists()else[];pending=[r for r in pending if r['status']=='pending-review'];known={r['path']for r in pending}
for f in incoming.rglob('*')if incoming.exists()else[]:
 if f.is_file()and f.name not in ['README.md','manifest.json']and f.relative_to(R).as_posix()not in known:
  pending.append({'id':'incoming-'+hashlib.sha256(f.read_bytes()).hexdigest()[:16],'path':f.relative_to(R).as_posix(),'originalFileName':f.name,'source':None,'note':'Manually added; no intake metadata yet.','status':'pending-review'})
thumbs=T/'thumbnails';thumbs.mkdir(exist_ok=True)
for r in rows:
 f=(R/r['path']).resolve();assert f.is_relative_to(R)
 if f.suffix.lower()in['.jpg','.jpeg','.png','.webp']:
  dst=thumbs/(r['id']+'.jpg')
  if not dst.exists():
   with Image.open(f)as image:
    image=ImageOps.exif_transpose(image).convert('RGB');image.thumbnail((520,320));image.save(dst,quality=82)
  r['_thumbnail']='thumbnails/'+dst.name
for r in rows:
 if r['path'].endswith('.pdf'):
  preview=next((x for x in rows if r['id']in(x.get('derivation')or{}).get('sourceAssetIds',[])and x.get('_thumbnail')),None)
  if preview:r['_thumbnail']=preview['_thumbnail']
data=json.dumps({'project':m['projectId'],'assets':rows,'incoming':pending},ensure_ascii=False).replace('<','\\u003c')
page=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Building reference catalog</title>
<style>*{box-sizing:border-box}body{font:15px system-ui,sans-serif;background:#f5f2e9;color:#193039;margin:0}header{padding:28px 4vw 20px;background:#e7e1d2;border-bottom:1px solid #cfc7b7}h1{margin:0 0 8px;font-size:28px}p{line-height:1.5}.intro{max-width:900px;color:#52636a}.filters{display:flex;flex-wrap:wrap;gap:10px;margin:16px 0}input,select,button{font:inherit;padding:10px;border:1px solid #aaa18f;background:#fffdf7;border-radius:5px}input{flex:1;min-width:230px}button{cursor:pointer}button:hover,a:hover{color:#8b4325}.links{display:flex;gap:20px;flex-wrap:wrap}a{color:#214e65}#count{font-weight:600;margin:12px 0 0}main{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:18px;padding:25px 4vw}article{background:#fff;border:1px solid #ded8cc;border-radius:6px;overflow:hidden;min-width:0}article h2{font-size:16px;margin:12px 0}article .body{padding:0 15px 15px}article img,.document{width:100%;height:180px;object-fit:contain;background:#eeeae1}.document{display:grid;place-items:center;color:#746958;font-size:22px}.tag{display:inline-block;border-radius:3px;background:#ecefe7;padding:3px 6px;font-size:12px;margin:4px 5px 0 0}.pending{background:#fff0cb}small{font-size:12px;color:#62625b;overflow-wrap:anywhere}details{margin-top:12px}pre{font:12px ui-monospace,monospace;white-space:pre-wrap;overflow-wrap:anywhere;max-height:330px;overflow:auto;background:#f7f6f2;padding:10px}footer{padding:10px 4vw 32px}#empty{padding:25px 4vw}label span{display:block;font-size:12px;margin-bottom:4px}#search{align-self:end}a.file{text-decoration:none;color:inherit}#more{display:block;margin:0 auto 20px}details summary{cursor:pointer;color:#214e65}@media(max-width:600px){header{padding:20px}main{padding:20px}select{max-width:90vw}h1{font-size:24px}}</style>
<header><h1 id="title">Reference catalog</h1><p class="intro">Real-building photographs, plans, sections and source records. Search current or original filenames, room names, archive IDs and provenance. Incoming files remain separate until reviewed.</p><nav class="links"><a href="../README.md">Library guide</a><a href="../manifest.json">Evidence manifest</a><a href="../incoming/manifest.json">Incoming manifest</a><a href="../manifest.schema.json">Schema</a></nav>
<div class="filters"><label><span>Collection</span><select id="scope"><option value="evidence">Verified evidence</option><option value="incoming">Incoming · pending review</option></select></label><input id="search" type="search" aria-label="Search references" placeholder="Room, filename, archive ID or source…"><label><span>Source role</span><select id="role"><option value="">All source roles</option></select></label><label><span>Kind</span><select id="kind"><option value="">All kinds</option></select></label><label><span>Space</span><select id="space"><option value="">All spaces</option></select></label><label><span>Level</span><select id="level"><option value="">All levels</option></select></label><button id="reset">Reset</button></div><p id="count" role="status"></p></header><p id="empty" hidden></p><main id="grid"></main><button id="more" hidden>Show more</button><footer><small>Local research library. Unknown rights are not permission to publish. Panorama face labels do not establish north. Historical and modern sources may show different building arrangements.</small></footer>
<script id="catalog-data" type="application/json">DATA</script><script>
const data=JSON.parse(document.getElementById('catalog-data').textContent),$=id=>document.getElementById(id);$('title').textContent=data.project+' · reference catalog';document.title=data.project+' · reference catalog';let limit=48;
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function link(path){return '../'+path.split('/').map(encodeURIComponent).join('/')}
for(const [key,values]of [['role',data.assets.map(r=>r.sourceRole?.value||'unknown')],['kind',data.assets.map(r=>r.kind)],['space',data.assets.flatMap(r=>r.location.spaces)],['level',data.assets.flatMap(r=>r.location.levels)]])for(const value of [...new Set(values)].sort()){$(key).append(new Option(value,value))}
function render(){const isPending=$('scope').value==='incoming',words=$('search').value.toLowerCase().trim().split(/\s+/).filter(Boolean);for(const k of ['role','kind','space','level'])$(k).disabled=isPending;const all=isPending?data.incoming:data.assets;const rows=all.filter(r=>words.every(w=>JSON.stringify(r).toLowerCase().includes(w))&&(isPending||((!$('role').value||(r.sourceRole?.value||'unknown')===$('role').value)&&(!$('kind').value||r.kind===$('kind').value)&&(!$('space').value||r.location.spaces.includes($('space').value))&&(!$('level').value||r.location.levels.includes($('level').value)))));$('count').textContent=rows.length+' of '+all.length+' '+(isPending?'incoming files · not verified':'evidence files');$('grid').replaceChildren();$('empty').hidden=rows.length>0;$('empty').textContent=isPending?'No pending files. Add new material to references/incoming/ and rebuild the catalog.':'No matching sources. Try fewer filters.';
for(const r of rows.slice(0,limit)){const card=el('article'),a=el('a',undefined,'file');a.href=link(r.path);if(r._thumbnail&&!isPending){const image=el('img');image.src=r._thumbnail;image.alt=r.title;image.loading='lazy';a.append(image)}else a.append(el('div',isPending?'Pending review':r.kind,'document'));const body=el('div',undefined,'body');a.append(el('h2',r.title||r.originalFileName));body.append(a);body.append(el('span',isPending?'Unverified':r.kind,'tag'+(isPending?' pending':'')));if(!isPending){body.append(el('span',r.sourceRole?.value||'unknown','tag'));for(const value of [...r.location.spaces,...r.location.levels])body.append(el('span',value,'tag'));body.append(el('p',r.description));body.append(el('small','Original: '+(r.originalFileNames.join(', ')||'unknown; received as '+r.ingestedFileName)))}else body.append(el('p',r.note||'Metadata and usefulness need review.'));const path=el('p');path.append(el('small',r.path));body.append(path);const details=el('details');details.append(el('summary','Metadata & provenance'));const clean={...r};delete clean._thumbnail;details.append(el('pre',JSON.stringify(clean,null,2)));body.append(details);card.append(body);$('grid').append(card)}$('more').hidden=rows.length<=limit}
for(const id of ['scope','search','role','kind','space','level'])$(id).addEventListener(id==='search'?'input':'change',()=>{limit=48;render()});$('more').addEventListener('click',()=>{limit+=48;render()});$('reset').addEventListener('click',()=>{for(const id of ['search','role','kind','space','level'])$(id).value='';$('scope').value='evidence';limit=48;render()});render();</script></html>'''.replace('DATA</script>',data+'</script>')
(T/'index.html').write_text(page,encoding='utf-8')
from urllib.parse import quote
index=['# Evidence index','','Generated from manifest.json. [HTML catalog](catalog/index.html). Pending incoming files are excluded.','','| Source | Kind | Location |','|---|---|---|']
for r in rows:index.append('| ['+r['title'].replace('|','/').replace('[','(').replace(']',')')+']('+quote(r['path'],safe='/')+') | '+r['kind']+' | '+', '.join(r['location']['spaces']+r['location']['levels']+r['location']['facades'])+' |')
(R/'INDEX.md').write_text('\n'.join(index)+'\n',encoding='utf-8')
print('Catalog built:',len(rows),'verified;',len(pending),'incoming')
